# Generated by Django 3.2.5 on 2022-12-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(upload_to='./shop_image/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
