# Generated by Django 3.2.5 on 2022-09-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[(1, 'تکمیل نشده'), (2, 'در انتظار تایید فروشگاه'), (3, 'در حال آماده سازی'), (4, 'در حال ارسال'), (5, 'دریافت شده'), (6, 'دریافت نشده')], default=1, max_length=25),
        ),
    ]
