# Generated by Django 3.2.5 on 2022-09-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='max_delivery_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='minimum_delivery_time',
            field=models.DateTimeField(null=True),
        ),
    ]
